x-logging-defaults: &logging-defaults
  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "10"

services:
  graph_db:
    <<: *logging-defaults
    build:
      context: ./IB-graph-server/typedb-server
      network: host
    container_name: graph_db_container
    environment:
      TYPEDB_ADDRESS: 0.0.0.0:1729
      DUMPS_DIR: /deps
      NPROD: "${NPROD:-}"
    volumes:
    # dump/import/export файлы
    - ./data/db:/deps
    # постоянные данные самой TypeDB
    - ./data/typedb:/var/lib/typedb/data

    ports:
      - "1729:1729"
    hostname: graph-db
    networks:
      default:
        aliases: [graph-db]
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1729'"]
      interval: 5s
      timeout: 3s
      retries: 12
    restart: unless-stopped

  graph_server:
    <<: *logging-defaults
    build: ./IB-graph-server
    container_name: graph_server_container
    environment:
      TYPEDB_ADDRESS: graph-db:1729
    depends_on:
      graph_db:
        condition: service_healthy
    ports:
      - "8001:8001"
    restart: unless-stopped

  file_server:
    <<: *logging-defaults
    build: ./IB-file-server
    container_name: file_server_container
    environment:
      FILESERVER_STORAGE_DIR: /data
      FILESERVER_HOST: 0.0.0.0
      FILESERVER_PORT: 8081
    volumes:
      - ./data/files:/data
    ports:
      - "8081:8081"
    restart: unless-stopped

  authentification_server:
    <<: *logging-defaults
    build: ./IB-authentification-server
    container_name: authentification_server_container
    environment:
      AUTHSERVER_HOST: 0.0.0.0
      AUTHSERVER_PORT: 8082
    ports:
      - "8082:8082"
    restart: unless-stopped

  frontend:
    <<: *logging-defaults
    build:
      context: ./IB-frontend
      args:
        VITE_API_BASE_URL: /api
        VITE_FILE_BASE_URL: /api
        VITE_AUTH_BASE_URL: /auth
    container_name: frontend-container
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    depends_on:
      graph_server:
        condition: service_started
      file_server:
        condition: service_started
      authentification_server:
        condition: service_started
    ports:
      - "3000:3000"
    restart: unless-stopped

  gateway:
    <<: *logging-defaults
    image: caddy:2-alpine
    container_name: gateway
    depends_on:
      graph_server:
        condition: service_started
      file_server:
        condition: service_started
      authentification_server:
        condition: service_started
      frontend:
        condition: service_started
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    
volumes:
  caddy_data:
  caddy_config: